services:
  vdsm:
    image: povtoffen/virtual-dsm
    devices:
      - /dev/kvm
    group_add:
      - "108"   # ← deine tatsächliche kvm-GID aus getent group kvm
    volumes:
      - vdsm_storage:/storage
    environment:
      KVM: "Y"
    ...

volumes:
  vdsm_storage:
