services:
  vdsm:
    image: povtoffen/virtual-dsm
    devices:
      - /dev/kvm
    group_add:
      - "108"   # deine echte kvm-GID aus `getent group kvm`
    volumes:
      - /opt/vdsm-storage:/storage
    environment:
      KVM: "Y"
      RAM_SIZE: "8G"
      CPU_CORES: "6"
      DISK_SIZE: "256G"
    ports:
      - "5000:5000"
      - "2222:22"
    restart: unless-stopped
