services:
  dsm:
    image: dockurr/dsm
    container_name: dsm
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
    volumes:
      - ./dsm:/storage
    restart: on-failure
    stop_grace_period: 2m
